# SPDX-License-Identifier: Apache-2.0
"""Zen Maru Gothic の woff2 を Google Fonts から取得して vendor/fonts/ に同梱する開発用スクリプト。

CSP (script-src 'self' / default-src 'self') のため実行時に Google Fonts CDN は使えない。
このスクリプトは開発時に一度だけ実行し、unicode-range 分割 woff2 と @font-face 定義
(vendor/fonts/zen-maru-gothic/fonts.css) を生成してリポジトリに同梱する。

usage: python scripts/fetch_fonts.py
"""

from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

FAMILY = "Zen Maru Gothic"
WEIGHTS = (500, 700, 900)
CSS2_URL = (
    "https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@500;700;900&display=swap"
)
# woff2 の unicode-range 分割 CSS を返させるためモダンブラウザの UA を名乗る
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)
OFL_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/zenmarugothic/OFL.txt"

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "vendor" / "fonts" / "zen-maru-gothic"

FONT_FACE_RE = re.compile(r"@font-face\s*\{[^}]*\}", re.S)
PROP_RE = re.compile(r"([a-z\-]+)\s*:\s*([^;]+);")
URL_RE = re.compile(r"url\((https://[^)]+\.woff2)\)")


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    css_text = fetch(CSS2_URL).decode("utf-8")

    faces = FONT_FACE_RE.findall(css_text)
    if not faces:
        print("css2 から @font-face を取得できませんでした", file=sys.stderr)
        return 1

    generated_blocks: list[str] = []
    downloaded = 0
    subset_counters: dict[int, int] = {weight: 0 for weight in WEIGHTS}
    for face in faces:
        props = dict(PROP_RE.findall(face))
        weight = int(props.get("font-weight", "0").strip())
        if weight not in WEIGHTS:
            continue
        url_match = URL_RE.search(face)
        if not url_match:
            continue
        remote_url = url_match.group(1)
        subset_counters[weight] += 1
        filename = f"zen-maru-gothic-{weight}-{subset_counters[weight]:03d}.woff2"
        target = OUT_DIR / filename
        if not target.exists():
            target.write_bytes(fetch(remote_url))
            downloaded += 1
        unicode_range = props.get("unicode-range", "").strip()
        block = (
            "@font-face {\n"
            f'  font-family: "{FAMILY}";\n'
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f'  src: url("./{filename}") format("woff2");\n'
        )
        if unicode_range:
            block += f"  unicode-range: {unicode_range};\n"
        block += "}"
        generated_blocks.append(block)

    fonts_css = OUT_DIR / "fonts.css"
    header = (
        "/* SPDX-License-Identifier: OFL-1.1 */\n"
        "/* Zen Maru Gothic (c) Yoshimichi Ohira — SIL Open Font License 1.1 (OFL.txt 参照) */\n"
        "/* generated by scripts/fetch_fonts.py — 手動編集しない */\n\n"
    )
    fonts_css.write_text(header + "\n\n".join(generated_blocks) + "\n", encoding="utf-8", newline="\n")

    ofl = OUT_DIR / "OFL.txt"
    if not ofl.exists():
        ofl.write_bytes(fetch(OFL_URL))

    total = sum(subset_counters.values())
    print(f"@font-face {total} 個 / 新規ダウンロード {downloaded} ファイル -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
